#!/bin/sh
# Generates the two pieces of nginx config that depend on the environment:
# the backend upstream, and whether view assets are cached.
#
# The nginx:alpine entrypoint sources every /docker-entrypoint.d/*.sh before
# starting nginx, so both files exist by the time default.conf is parsed.
# conf.d/*.conf is included in the http context, which is where the upstream
# and the cache zone belong; the .inc file is pulled in by the location that
# uses it.
set -eu

CONF_DIR=/etc/nginx/conf.d
BACKEND_SERVERS=${BACKEND_SERVERS:-backend:8000}
API_ASSET_CACHE_SECONDS=${API_ASSET_CACHE_SECONDS:-30}

# ---------- upstream ----------
# One entry is the single-backend case. Several entries balance across backend
# replicas: least_conn rather than round-robin, because agent runs are long and
# wildly uneven in duration, so request count is a poor proxy for load.
{
    echo "# Generated by 20-agents-hub-config.sh from BACKEND_SERVERS."
    echo "upstream agents_hub_backend {"
    echo "    least_conn;"
    for server in $BACKEND_SERVERS; do
        # A replica that keeps failing is parked for 10s rather than kept in
        # rotation. With a single backend this changes nothing: nginx always
        # retries the last remaining server.
        echo "    server ${server} max_fails=3 fail_timeout=10s;"
    done
    echo "    keepalive 32;"
    echo "}"
} > "$CONF_DIR/agents-hub-upstream.conf"

# ---------- view-asset cache ----------
# Included by the /api/views/*/assets/ location. Written in both branches so
# the include never dangles.
if [ "$API_ASSET_CACHE_SECONDS" -gt 0 ] 2>/dev/null; then
    cat > "$CONF_DIR/agents-hub-api-cache-zone.conf" <<ZONE
# Generated by 20-agents-hub-config.sh.
proxy_cache_path /var/cache/nginx/agents_hub_api levels=1:2
    keys_zone=agents_hub_api:10m max_size=512m inactive=10m use_temp_path=off;
ZONE
    cat > "$CONF_DIR/agents-hub-api-cache.inc" <<INC
# Generated by 20-agents-hub-config.sh (API_ASSET_CACHE_SECONDS=$API_ASSET_CACHE_SECONDS).
proxy_cache agents_hub_api;
proxy_cache_key "\$scheme\$request_method\$host\$request_uri";
proxy_cache_valid 200 206 ${API_ASSET_CACHE_SECONDS}s;
proxy_cache_valid 404 5s;
proxy_cache_methods GET HEAD;
# One upstream fetch per asset under a render storm, and a cached copy is still
# served while the backend restarts or a refresh is in flight.
proxy_cache_lock on;
proxy_cache_use_stale error timeout updating http_502 http_503 http_504;
proxy_cache_background_update on;
add_header X-Cache-Status \$upstream_cache_status always;
INC
else
    : > "$CONF_DIR/agents-hub-api-cache-zone.conf"
    cat > "$CONF_DIR/agents-hub-api-cache.inc" <<'INC'
# Generated by 20-agents-hub-config.sh (API_ASSET_CACHE_SECONDS=0 — disabled).
proxy_cache off;
proxy_buffering off;
INC
fi
