import { useCallback, useEffect, useMemo, useRef } from 'react';
import {
  estimateFlowCost, getFlow, getFlowInstances, getFlowLogs, getFlowRuns, resumeFlowRun,
  runFlow, runFlowNode, stopFlow,
} from '../../api';
import { errorDetail } from '../toast';
import { useStream } from '../stream';
import { reconstructRunMessages } from './runFormat';
import { NODE_LIFECYCLE_TYPES } from './graphHelpers';

// A fresh, unique token per chat thread. Generated on mount and regenerated by
// "New chat" so each thread gets its own conversation id. It must be unique
// (not a 0-based counter): the conversation id derives from it deterministically
// and resetting to a counter on reload would collide with already-persisted
// conversations (reusing their record + showing their old logs).
export const newChatNonce = () => `${Date.now().toString(36)}${Math.random().toString(36).slice(2, 8)}`;

/**
 * Everything about executing the flow and watching it run: the runs list and
 * History records, the live chat-stream translation into flow-log events, the
 * derived node statuses and log slices the canvas/Logs panel render, and the
 * run/stop/resume/estimate actions. The document itself (flow, nodes, edges,
 * saving) is useFlowDocument's; `persistFlow` and `loadWorkspaceTasks` are
 * passed in from there because a manual Run flushes unsaved edits first.
 */
export function useFlowRuns(deps) {
  const {
    chatNonce, flow, flowId, flowSessionId, liveUpdates, loadWorkspaceTasks, logs,
    nodes, persistFlow, resumedChat, running, runs,
    selectedNode, selectedNodeId, selectedRunGroup, selectedWorkspace, setCenterTab,
    setChatNonce, setEstimate, setEstimating, setFlow, setFlowSessionId, setInstances, setLogs,
    setResumedChat, setResumingRun, setRightTab, setRunNodeId, setRunning, setRuns,
    setSelectedNodeId, setSelectedRunGroup, setStopping, setStreamLogs, streamLogs,
    t, toast,
  } = deps;

  // node_id -> display label, captured from each turn's flow_meta so node_start /
  // node_done lines can show the agent name even though only flow_meta carries
  // the full node list.
  const nodeLabelsRef = useRef({});
  // True between a chat turn's flow_meta and its done, so the SSE flow_runs
  // listener can stand down while the stream is driving the view.
  const chatStreamingRef = useRef(false);

  // The conversation id FlowChat uses for the active chat. It is also the
  // run_group the backend stamps on this chat's flow-log events, so we can
  // scope the live Logs view to just the current chat. A resumed record keeps
  // its own id so continued turns grow that same record.
  const activeConversationId = resumedChat
    ? resumedChat.conversationId
    : chatNonce
    ? `flow-chat-${flowId}-${chatNonce}`
    : `flow-chat-${flowId}`;

  // The slice of `logs` (which holds every conversation's events for this flow)
  // relevant to what's on screen right now. Everything live, canvas node
  // statuses, the "executing" flag, the Logs panel, derives from THIS, never the
  // global `logs` tail. Scoping to the active conversation is what makes "New
  // chat" reset the view: a fresh conversation id has no events here, instead of
  // inheriting the previous chat's trailing flow_start/agent_start lines.
  const scopedLogs = useMemo(() => {
    // A selected History record -> only its events.
    if (selectedRunGroup) return logs.filter((l) => l.run_group === selectedRunGroup);
    // Manual Run / Run-node -> the most recent live run_group's tail.
    if (running || flow?.running) {
      const liveGroup = logs[logs.length - 1]?.run_group;
      return liveGroup ? logs.filter((l) => l.run_group === liveGroup) : logs;
    }
    // Chat -> live events streamed straight from the run (no refetch). streamLogs
    // is reset per conversation, so a fresh chat starts empty just like before.
    return streamLogs;
  }, [logs, streamLogs, selectedRunGroup, running, flow?.running]);

  const handleNewChat = () => {
    setChatNonce(newChatNonce());
    setCenterTab('chat');
    setResumedChat(null); // leave any resumed record; show the new (empty) chat
    setSelectedRunGroup(null);
    setSelectedNodeId(null);
  };

  const loadLogs = useCallback(async (workspaceName) => {
    if (!workspaceName) return;
    try {
      const response = await getFlowLogs(flowId, workspaceName);
      setLogs(response.data || []);
    } catch (error) {
      console.error('Failed to load logs', error);
    }
  }, [flowId, setLogs]);

  const loadRuns = useCallback(async (workspaceName) => {
    try {
      const response = await getFlowRuns(flowId, workspaceName || undefined);
      setRuns(response.data || []);
    } catch (error) {
      console.error('Failed to load runs', error);
    }
    try {
      const { data } = await getFlowInstances(flowId);
      const byId = {};
      (data || []).forEach((record) => {
        if (record?.flow_run_id) byId[record.flow_run_id] = record;
      });
      setInstances(byId);
    } catch (error) {
      console.error('Failed to load run records', error);
    }
  }, [flowId, setInstances, setRuns]);

  // Refresh logs + runs once at the end of a chat turn so the History list and
  // the persisted record catch up. Live progress no longer comes from here (see
  // handleStreamEvent), this is just the closing reconcile.
  const handleChatActivity = useCallback(() => {
    // Turn ended (normally, or via Stop/error where no `done` arrives): clear the
    // streaming guard so the SSE listener resumes, then reconcile once.
    chatStreamingRef.current = false;
    const ws = flow?.workspace || selectedWorkspace;
    if (!ws) return;
    loadLogs(ws);
    loadRuns(ws);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [flow?.workspace, selectedWorkspace]);

  // Translate a raw chat-stream event into the flow-log event shape the editor's
  // derivations (isExecuting, activeNodeId, nodeStatuses, FlowLog) consume, and
  // append it to the live stream-log buffer. This is the heart of the
  // stream-driven live view: every status the user sees during a chat run comes
  // from here, not from polling the backend.
  const handleStreamEvent = useCallback((event) => {
    const evType = event?.type;
    if (!evType) return;
    const ts = new Date().toISOString();
    if (evType === 'flow_meta') {
      const labels = {};
      for (const n of event.nodes || []) labels[n.node_id] = n.agent_label || n.agent_id;
      nodeLabelsRef.current = labels;
      chatStreamingRef.current = true;
      setStreamLogs((prev) => [...prev, { type: 'flow_start', timestamp: ts, content: t('flowEditor.flowStarted'), state: event.state, title: event.user_message }]);
    } else if (evType === 'node_start') {
      const label = event.agent_label || nodeLabelsRef.current[event.node_id] || event.agent_id || 'Agent';
      setStreamLogs((prev) => [...prev, {
        type: 'agent_start', node_id: event.node_id, agent_id: event.agent_id,
        agent_name: label, tag: 'agent', content: `Running ${label}`, timestamp: ts,
      }]);
    } else if (evType === 'node_done') {
      const label = event.agent_label || nodeLabelsRef.current[event.node_id] || event.agent_id || 'Agent';
      setStreamLogs((prev) => [...prev, {
        type: event.ok ? 'agent_finish' : 'agent_error', node_id: event.node_id,
        agent_id: event.agent_id, agent_name: label, tag: 'agent',
        content: event.ok ? `Completed ${label}` : `${label} failed`,
        output: event.response || event.error || '', timestamp: ts,
        // Post-node shared-state snapshot for the live Runtime State block.
        state: event.state,
      }]);
    } else if (evType === 'node_skip') {
      setStreamLogs((prev) => [...prev, {
        type: 'node_skip', node_id: event.node_id,
        agent_name: nodeLabelsRef.current[event.node_id] || 'Node', content: 'Skipped', timestamp: ts,
      }]);
    } else if (evType === 'done') {
      chatStreamingRef.current = false;
      setStreamLogs((prev) => [...prev, {
        type: event.ok === false ? 'flow_stopped' : 'flow_finish',
        content: event.ok === false ? t('flowEditor.flowStopped') : t('flowEditor.flowFinished'), timestamp: ts,
      }]);
    }
  }, [setStreamLogs, t]);

  // A fresh conversation (new chat / resumed record / flow change) starts with an
  // empty live buffer so it doesn't inherit the previous chat's execution trail.
  useEffect(() => {
    setStreamLogs([]);
    nodeLabelsRef.current = {};
    chatStreamingRef.current = false;
  }, [activeConversationId]); // eslint-disable-line react-hooks/exhaustive-deps

  const { on } = useStream();
  useEffect(() => {
    const workspaceName = flow?.workspace || selectedWorkspace;
    if (!workspaceName) return;
    loadWorkspaceTasks(workspaceName);
    loadLogs(workspaceName);
    loadRuns(workspaceName);
    if (!liveUpdates) return undefined;
    return on('app', async (ev) => {
      if (ev.type !== 'flow_runs.changed' && ev.type !== 'tasks.changed') return;
      // While a chat run is streaming, the live view is driven entirely by the
      // stream (handleStreamEvent); the backend emits a flow_runs.changed per log
      // event, so refetching here would be exactly the redundant churn we set out
      // to remove. Skip it, FlowChat's turn-end onActivity reconciles the
      // History list once the run finishes. Manual flow runs (flow.running) and
      // task changes still refetch normally.
      if (chatStreamingRef.current) return;
      loadLogs(workspaceName);
      loadRuns(workspaceName);
      if (flow?.running) {
        try {
          const res = await getFlow(flowId);
          setFlow((prev) => ({ ...prev, running: res.data.running }));
        } catch { /* keep the last known running state */ }
      }
    });
  }, [flowId, flow?.workspace, flow?.running, selectedWorkspace, liveUpdates, on, loadLogs, loadRuns]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    if (!selectedNodeId) return;
    // When a History record is being viewed, keep the Logs tab open and let
    // `visibleLogs` scope the stream to this node (logs for this node within
    // this record) instead of jumping to the Node inspector. Outside of a
    // selected record, open the inspector so the node's edits are visible.
    setRightTab(selectedRunGroup ? 'logs' : 'graph');
  }, [selectedNodeId]); // eslint-disable-line react-hooks/exhaustive-deps

  const activeNodeId = useMemo(() => {
    // Derive the running node from the log stream rather than flow.running, so
    // this works for both runFlow() runs and chat-driven runs (which don't flip
    // the flow's running flag). Scoped to the current conversation/run so a fresh
    // chat clears the highlight. If the flow has ended, nothing is active.
    if (scopedLogs.length) {
      const lastFlowEvent = [...scopedLogs].reverse().find(
        (l) => l.type === 'flow_finish' || l.type === 'flow_stopped'
      );
      const lastStart = [...scopedLogs].reverse().find((l) => l.type === 'flow_start');
      const ended = lastFlowEvent && (!lastStart || scopedLogs.indexOf(lastFlowEvent) > scopedLogs.indexOf(lastStart));
      if (ended) return null;
    }
    const lastType = {};
    for (const log of scopedLogs) {
      if (log.node_id && NODE_LIFECYCLE_TYPES.has(log.type)) lastType[log.node_id] = log.type;
    }
    return Object.entries(lastType).find(([, ty]) => ty === 'agent_start')?.[0] ?? null;
  }, [scopedLogs]);

  // True while a run is in progress, covers runFlow() (flow.running) and
  // chat-driven runs (latest flow-level log event is flow_start, not yet
  // finished/stopped). Used to drive the Logs auto-scroll.
  const isExecuting = useMemo(() => {
    if (running || flow?.running) return true;
    if (!scopedLogs.length) return false;
    for (let i = scopedLogs.length - 1; i >= 0; i -= 1) {
      const ty = scopedLogs[i].type;
      if (ty === 'flow_finish' || ty === 'flow_stopped') return false;
      if (ty === 'flow_start') return true;
    }
    return false;
  }, [running, flow?.running, scopedLogs]);

  // When a run starts (rising edge of isExecuting), open the Logs tab so the
  // user sees execution progress. Only fires on the transition, so it won't
  // fight the user if they switch back to Graph mid-run.
  const wasExecutingRef = useRef(false);
  useEffect(() => {
    if (isExecuting && !wasExecutingRef.current) {
      // A fresh run started, drop any historical selection so the live stream shows.
      setSelectedRunGroup(null);
      setRightTab('logs');
    }
    wasExecutingRef.current = isExecuting;
  }, [isExecuting]); // eslint-disable-line react-hooks/exhaustive-deps

  // A live History record for the active chat run, built from the stream buffer
  // so the run shows up the moment it starts, with a status derived from the
  // latest boundary event (running -> completed/stopped), instead of only after
  // it finishes. The persisted record (loaded at turn end) takes over once it
  // exists, since it carries richer events for resume/replay.
  const liveChatRun = useMemo(() => {
    if (!streamLogs.length) return null;
    let status = 'running';
    for (let i = streamLogs.length - 1; i >= 0; i -= 1) {
      const ty = streamLogs[i].type;
      if (ty === 'flow_finish') { status = 'completed'; break; }
      if (ty === 'flow_stopped') { status = 'stopped'; break; }
      if (ty === 'flow_start') { status = 'running'; break; }
    }
    // Title the record by the conversation's first message (truncated), matching
    // the persisted record once it loads. Fall back to a generic label until the
    // first flow_start carries the message.
    const firstMsg = (streamLogs.find((l) => l.type === 'flow_start' && l.title)?.title || '').trim().replace(/\n/g, ' ');
    const title = firstMsg
      ? firstMsg.slice(0, 60) + (firstMsg.length > 60 ? '…' : '')
      : t('flowEditor.flowChat');
    return {
      run_group: activeConversationId,
      kind: 'chat',
      title,
      started_at: streamLogs[0]?.timestamp,
      status,
      events: streamLogs,
    };
  }, [streamLogs, t, activeConversationId]);

  const displayRuns = useMemo(() => {
    if (!liveChatRun) return runs;
    // Once the persisted record exists (post-reconcile), prefer it.
    if (runs.some((r) => r.run_group === liveChatRun.run_group)) return runs;
    return [liveChatRun, ...runs];
  }, [runs, liveChatRun]);

  const selectedRun = useMemo(
    () => displayRuns.find((r) => r.run_group === selectedRunGroup) || null,
    [displayRuns, selectedRunGroup]
  );

  // Session to stream live agent output from. Null while a history record is
  // open, that view is a replay, and mixing a live run into it would be a lie.
  // Falls back to the running record's session so a flow already in flight when
  // the page loaded still streams.
  const liveSessionId = useMemo(() => {
    if (selectedRun) return null;
    if (flowSessionId) return flowSessionId;
    if (!(running || flow?.running)) return null;
    return displayRuns.find((r) => r.status === 'running')?.session_id || null;
  }, [selectedRun, flowSessionId, running, flow?.running, displayRuns]);

  // The log stream the right column renders:
  //  - a selected History record -> that record's own events
  //  - otherwise -> the run-scoped slice (scopedLogs). For chat this is the live
  //    stream buffer, which PERSISTS after the run ends so the finished run's
  //    logs + node statuses stay on screen until "New chat" clears them. A fresh
  //    chat has an empty buffer, so agents still read as pending when idle.
  const baseLogs = useMemo(() => {
    if (selectedRun) return selectedRun.events || [];
    return scopedLogs;
  }, [selectedRun, scopedLogs]);

  // Reconstruct the conversation bubbles for a selected History record from its
  // flow-log events (see reconstructRunMessages).
  const runMessages = useMemo(() => {
    if (!selectedRun) return [];
    return reconstructRunMessages(selectedRun);
  }, [selectedRun]);

  const visibleLogs = useMemo(() => {
    if (!selectedNode) return baseLogs;
    return baseLogs.filter(
      (log) => log.node_id === selectedNode.id || log.agent_id === selectedNode.data.agent_id
    );
  }, [baseLogs, selectedNode]);

  // Per-node execution status derived from the latest log line for each node:
  //  - done:    finished, skipped, errored, or stopped
  //  - running: agent_start is the most recent event
  //  - pending: a run is in progress but this node hasn't started yet
  //  - ready:   no run in progress (fresh/idle chat) and no event for this node
  const nodeStatuses = useMemo(() => {
    const lastType = {};
    for (const log of baseLogs) {
      if (log.node_id && NODE_LIFECYCLE_TYPES.has(log.type)) lastType[log.node_id] = log.type;
    }
    // Whether the displayed run is still executing. Untouched nodes read as
    // "pending" mid-run (future steps) but "ready" on a fresh/idle chat.
    let runActive = running || flow?.running || false;
    if (!runActive) {
      for (let i = baseLogs.length - 1; i >= 0; i -= 1) {
        const ty = baseLogs[i].type;
        if (ty === 'flow_finish' || ty === 'flow_stopped') break;
        if (ty === 'flow_start') { runActive = true; break; }
      }
    }
    const DONE = new Set(['agent_finish', 'node_skip', 'agent_error', 'agent_stopped']);
    return nodes.map((node) => {
      const ty = lastType[node.id];
      let status = runActive ? 'pending' : 'ready';
      if (ty === 'agent_start') status = 'running';
      else if (DONE.has(ty)) status = ty === 'agent_error' ? 'error' : 'done';
      return {
        id: node.id,
        label: node.data?.label || node.data?.agent_id || 'Agent',
        status,
      };
    });
  }, [baseLogs, nodes, running, flow?.running]);

  const handleRunFlow = async () => {
    if (!flow) return;
    const workspaceName = flow.workspace || selectedWorkspace;
    if (!workspaceName) {
      alert(t('flowEditor.selectWorkspaceFirst'));
      return;
    }
    const saved = await persistFlow({ workspace: workspaceName });
    if (!saved) return;
    setRunning(true);
    try {
      const started = await runFlow(flowId, {
        workspace: workspaceName,
        description: flow.description || '',
        task_id: flow.task_id || undefined,
      });
      // The run endpoint prices the flow on the way out, so what a run is about
      // to cost lands in front of whoever pressed Run, not only on Estimate.
      const cost = started?.data?.estimated_cost;
      if (cost && typeof cost.total_usd === 'number') {
        toast.success(t('flowEditor.runStarted'), t('flowEditor.estimatedCost', { usd: cost.total_usd.toFixed(4) }));
      }
      setFlowSessionId(started?.data?.session_id || null);
      setFlow((prev) => ({ ...prev, running: true }));
      await loadLogs(workspaceName);
      setRightTab('logs');
    } catch (error) {
      alert(`Failed to start flow: ${error.response?.data?.detail || error.message}`);
    } finally {
      setRunning(false);
    }
  };

  const handleEstimate = async () => {
    setEstimating(true);
    try {
      const { data } = await estimateFlowCost(flowId);
      setEstimate(data);
    } catch (error) {
      toast.error(t('flowEditor.estimateFailed'), errorDetail(error));
    } finally {
      setEstimating(false);
    }
  };

  const handleResumeRun = async (flowRunId) => {
    setResumingRun(flowRunId);
    try {
      await resumeFlowRun(flowRunId);
      toast.success(t('flowEditor.runResumed'));
      await loadRuns(flow?.workspace || selectedWorkspace);
    } catch (error) {
      toast.error(t('flowEditor.resumeFailed'), errorDetail(error));
    } finally {
      setResumingRun(null);
    }
  };

  const handleStopFlow = async () => {
    if (!flow) return;
    setStopping(true);
    try {
      await stopFlow(flowId);
      const updated = await getFlow(flowId);
      setFlow(updated.data);
    } catch (error) {
      alert(`Failed to stop flow: ${error.response?.data?.detail || error.message}`);
    } finally {
      setStopping(false);
    }
  };

  const handleRunNode = async (nodeId) => {
    if (!flow) return;
    const workspaceName = flow.workspace || selectedWorkspace;
    if (!workspaceName) {
      alert(t('flowEditor.selectWorkspaceFirst'));
      return;
    }
    const saved = await persistFlow({ workspace: workspaceName });
    if (!saved) return;
    setRunNodeId(nodeId);
    setSelectedNodeId(nodeId);
    try {
      await runFlowNode(flowId, {
        node_id: nodeId,
        workspace: workspaceName,
        description: flow.description || '',
      });
      await loadLogs(workspaceName);
      setRightTab('logs');
    } catch (error) {
      alert(`Failed to run node: ${error.response?.data?.detail || error.message}`);
    } finally {
      setRunNodeId(null);
    }
  };

  return {
    activeConversationId, activeNodeId, baseLogs, displayRuns, handleChatActivity,
    handleEstimate, handleNewChat, handleResumeRun, handleRunFlow, handleRunNode,
    handleStopFlow, handleStreamEvent, isExecuting, liveSessionId, loadLogs, loadRuns,
    nodeStatuses, runMessages, scopedLogs, selectedRun, visibleLogs,
  };
}

export default useFlowRuns;
