# Optional: Default model selection
OPENAI_NON_REASONING_MODEL_NAME = "gpt-4.1"
# OPENAI_NON_REASONING_MODEL_NAME = "gpt-4.1-mini"
# OPENAI_NON_REASONING_MODEL_NAME = "gpt-4.1-nano"
OPENAI_REASONING_MODEL_NAME = "o3"
